Bdu 83 revamp big dipper landing page
forbole/big-dipper-landing-revamp pull request #39
Opened 2022-08-21 02:32 UTC by teamchong

Closes #36 
Closes #26 
Closes #12 
Closes #11 
Closes #10 
Closes #9 
Closes #8 

## Checklist
- [X] Ran Linting
- [X] Targeted PR against correct branch.
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Wrote unit tests.
- [X] Added an entry to the `CHANGELOG.md` file.
- [X] Re-reviewed `Files changed` in the Github PR explorer.

2022-08-23 13:08 UTC, teamchong commented on .github/workflows/test.yml
> +    - uses: actions/setup-node@v3
ff

2022-08-23 18:07 UTC, yayay927 requested changes
Hi Steven, since I noticed there are some parts different from design, I'm going to leave all the comments about UI in this pr.

1. Current home page background color gradient (image 2) doesn't fit design wireframe (image 1)
<img width="567" alt="截圖 2022-08-24 上午1 56 10" src="https://user-images.githubusercontent.com/32444273/186231058-56d74c08-0bfe-4322-9fdc-9af6edc07e38.png">
(image 1)
<img width="1439" alt="截圖 2022-08-24 上午1 59 00" src="https://user-images.githubusercontent.com/32444273/186231162-4ef056b8-1cf5-4be9-a27e-47ff3a7f2bdf.png">
(image 2)

2. Supported networks page -- row number in your staging (8) doesn't fit design wireframe (5)
<img width="562" alt="截圖 2022-08-24 上午2 01 52" src="https://user-images.githubusercontent.com/32444273/186231494-87e6677f-3e53-4ae0-acfb-22cfacf9c06f.png">

3. Circled arrow under supported networks component doesn't fit design wireframe, which should be a round circle instead of an oval
<img width="1128" alt="截圖 2022-08-24 上午2 02 34" src="https://user-images.githubusercontent.com/32444273/186231638-0f26eea6-60f1-4767-9da9-305fd2921776.png">

4. There are colors for different selected in design wireframe for menu items
<img width="351" alt="截圖 2022-08-24 上午2 06 33" src="https://user-images.githubusercontent.com/32444273/186232355-8499bda1-1c55-4726-aec9-53bab778153b.png">

5. Font for menu is different from design wireframe (as image above)

2022-09-12 14:09 UTC, teamchong commented
> Hi Steven, since I noticed there are some parts different from design, I'm going to leave all the comments about UI in this pr.
> 
> 1. Current home page background color gradient (image 2) doesn't fit design wireframe (image 1)
>    (image 1)
> 
> <img alt="截圖 2022-08-24 上午1 56 10" width="567" src="https://user-images.githubusercontent.com/32444273/186231058-56d74c08-0bfe-4322-9fdc-9af6edc07e38.png">
> 
> (image 2) <img alt="截圖 2022-08-24 上午1 59 00" width="1439" src="https://user-images.githubusercontent.com/32444273/186231162-4ef056b8-1cf5-4be9-a27e-47ff3a7f2bdf.png">
> 
> 2. Supported networks page -- row number in your staging (8) doesn't fit design wireframe (5)
> 
> <img alt="截圖 2022-08-24 上午2 01 52" width="562" src="https://user-images.githubusercontent.com/32444273/186231494-87e6677f-3e53-4ae0-acfb-22cfacf9c06f.png">
> 
> 3. Circled arrow under supported networks component doesn't fit design wireframe, which should be a round circle instead of an oval
> 
> <img alt="截圖 2022-08-24 上午2 02 34" width="1128" src="https://user-images.githubusercontent.com/32444273/186231638-0f26eea6-60f1-4767-9da9-305fd2921776.png">
> 
> 4. There are colors for different selected in design wireframe for menu items
> 
> <img alt="截圖 2022-08-24 上午2 06 33" width="351" src="https://user-images.githubusercontent.com/32444273/186232355-8499bda1-1c55-4726-aec9-53bab778153b.png">
> 
> 5. Font for menu is different from design wireframe (as image above)

done

2022-09-13 23:16 UTC, teamchong commented
@yayay927 please help to follow up

2022-09-23 15:22 UTC, yayay927 requested changes
<img width="1440" alt="截圖 2022-09-23 下午4 17 32" src="https://user-images.githubusercontent.com/32444273/191995160-eb149761-5cf5-4ea9-90e5-bfed9f85d53c.png">
Need more margin top above header. Right now the logo and buttons are too close to the top.

<img width="572" alt="截圖 2022-09-23 下午4 20 22" src="https://user-images.githubusercontent.com/32444273/191995806-eeb3ff5d-7f6c-446f-b0db-432585d21e08.png">
The hover animation of chosen button brights up in the last second too suddenly. Unlike the natural hover animation of white unchosen items.

2022-09-23 15:29 UTC, yayay927 requested changes
<img width="1440" alt="截圖 2022-09-23 下午4 24 32" src="https://user-images.githubusercontent.com/32444273/191996765-71132347-ed60-4899-adec-eeffcbdc3933.png">
(3) Right now the white title is displayed in different height in different carousel images. Which creates a popping/moving visual effect for users and it's not very comfortable to stare at, especially when wanting to read the titles and descriptions carefully. Is it possible to make them in same horizontal line?
(4) The same with above, the main images are in different sizes, which also creates the kind of popping visual effect. Is it possible to adjust them into same visual size on page?

2022-09-23 16:15 UTC, teamchong commented
> <img alt="截圖 2022-09-23 下午4 17 32" width="1440" src="https://user-images.githubusercontent.com/32444273/191995160-eb149761-5cf5-4ea9-90e5-bfed9f85d53c.png">
> 
> (1) Need more margin top above header. Right now the logo and buttons are too close to the page top.
> <img alt="截圖 2022-09-23 下午4 20 22" width="572" src="https://user-images.githubusercontent.com/32444273/191995806-eeb3ff5d-7f6c-446f-b0db-432585d21e08.png">
I had reduce the logo size
> 
> (2) The hover animation of chosen button brights up in the last second too suddenly. Unlike the natural hover animation of white unchosen items.

removed hover effect for active menu item

2022-09-23 16:35 UTC, merged